<?php

namespace ACI\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
      public function readQuery( $order_by, $order_dir="ASC"){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT p.id,p.name FROM FrontendBundle:Page p ORDER BY p.$order_by $order_dir");
      
        
        return $query;
    }
      public function readSite($site){
        $em = $this->getEntityManager();        
        $query = $em->createQuery("SELECT p.id,p.name FROM FrontendBundle:Page p WHERE p.site=$site");
      
        
        return $query;
    }
  
    public function readAll($order_by='id'){
        return $this->readQuery($order_by)->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
    public function findBySite($site){
        return $this->readSite($site)->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
    public function count($query){
        return count($query->getSingleResult());
    }
    
    public function countAll(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM FrontendBundle:Menu p");
        return count($query->getSingleResult());
    }
}
