<?php

namespace ACI\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    
        public function readQuery( $order_by, $order_dir="ASC"){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT p FROM AppBundle:Menu p ORDER BY p.$order_by $order_dir");
      
        
        return $query;
    }
  
    public function readAll($order_by='position'){
        return $this->readQuery($order_by)->getResult();
    }
    
    public function count($query){
        return count($query->getSingleResult());
    }
    
    public function countAll(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM AppBundle:Menu p");
        return count($query->getSingleResult());
    }
}
