<?php

namespace ACI\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
      public function readQuery( $order_by, $order_dir="ASC"){
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT p.id,p.name FROM AppBundle:Site p ORDER BY p.$order_by $order_dir");
        $query1 = $this->_addAcl($query);
        
        return $query;
    }
  
    public function readAll($order_by='id'){
        return $this->readQuery($order_by)->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
    
    public function count($query){
        return count($query->getSingleResult());
    }
    
    public function countAll(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM AppBundle:Menu p");
        return count($query->getSingleResult());
    }
    
    
}
