<?php

namespace ACI\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {

    public function findCountry($name) {
        $dql = 'SELECT c FROM ACI\BackendBundle\Entity\Country c WHERE c.name= ' . '"' . $name . '"' . "'";
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        return $query->getOneOrNullResult();
    }

}
