<?php

namespace ACI\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends EntityRepository {

    public function findIndustry($name) {
        $dql = 'SELECT c FROM ACI\BackendBundle\Entity\Industry c WHERE c.name= ' . '"' . $name . '"' . "'";
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        return $query->getOneOrNullResult();
    }

    public function datatable($offset = null, $limit = null, $order = null, $dir = null, $sSearch = null) {
        $dql = "SELECT c FROM ACI\BackendBundle\Entity\Industry c WHERE c.id LIKE :sSearch OR c.name LIKE :sSearch OR c.sic LIKE :sSearch OR c.naics LIKE :sSearch OR c.naics_clasification LIKE :sSearch  ORDER BY c.{$order} {$dir}";

        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $query->setParameter("sSearch", '%' . $sSearch . '%');
        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        return $query->getResult();
    }

}
